[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
ffi = true
fs_permissions = [{ access = "read", path = "./reference" }]
gas_reports = ["PBEAR", "RankedShares"]
gas_limit = "18446744073709551615"
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
]

[fuzz]
runs = 256
