"""Emit src/noir/lib/Poseidon2.sol from reference/noir/poseidon2_params.py.

Usage, from `reference/`: python3 -m noir.tools.gen_poseidon2_sol

The permutation is emitted fully unrolled: all 64 rounds in a straight line, every
round constant a literal in the Yul. There is no constants blob and no memory, so a
round's constant costs one PUSH32 instead of a `mload` of a table that first had to
be copied out of the code. The four diagonal terms are literals too, bound once to
stack variables because they are reused by every one of the 56 partial rounds.
"""

import os

from noir.poseidon2_params import INTERNAL_DIAG, ROUND_CONSTANTS

HERE = os.path.dirname(os.path.abspath(__file__))

ROUNDS_F_HALF = 4
ROUNDS_P = 56
IND = " " * 12

EXTERNAL = """{i}{{
{i}    let t0 := addmod(a, b, P)
{i}    let t1 := addmod(c, d, P)
{i}    let t2 := addmod(addmod(b, b, P), t1, P)
{i}    let t3 := addmod(addmod(d, d, P), t0, P)
{i}    let t4 := addmod(mulmod(4, t1, P), t3, P)
{i}    let t5 := addmod(mulmod(4, t0, P), t2, P)
{i}    a := addmod(t3, t5, P)
{i}    b := t5
{i}    c := addmod(t2, t4, P)
{i}    d := t4
{i}}}""".format(i=IND)


def sbox(var, rc):
    """Add this round's constant to one element and raise it to the fifth power."""
    return (
        "{i}{{\n"
        "{i}    let x := addmod({v}, 0x{rc:064x}, P)\n"
        "{i}    let x2 := mulmod(x, x, P)\n"
        "{i}    {v} := mulmod(mulmod(x2, x2, P), x, P)\n"
        "{i}}}"
    ).format(i=IND, v=var, rc=rc)


def full_round(r):
    out = [sbox(v, ROUND_CONSTANTS[r][i]) for i, v in enumerate("abcd")]
    out.append(EXTERNAL)
    return "\n".join(out)


def partial_round(r):
    return "\n".join(
        [
            sbox("a", ROUND_CONSTANTS[r][0]),
            "{i}{{".format(i=IND),
            "{i}    let sum := addmod(addmod(a, b, P), addmod(c, d, P), P)".format(i=IND),
            "{i}    a := addmod(mulmod(a, d0, P), sum, P)".format(i=IND),
            "{i}    b := addmod(mulmod(b, d1, P), sum, P)".format(i=IND),
            "{i}    c := addmod(mulmod(c, d2, P), sum, P)".format(i=IND),
            "{i}    d := addmod(mulmod(d, d3, P), sum, P)".format(i=IND),
            "{i}}}".format(i=IND),
        ]
    )


def rounds():
    parts = [
        "{i}// initial external linear layer".format(i=IND),
        EXTERNAL,
    ]
    for r in range(ROUNDS_F_HALF):
        parts.append("{i}// full round {r}".format(i=IND, r=r))
        parts.append(full_round(r))
    parts.append("{i}// partial rounds: the constant and the S-box on element 0 only,".format(i=IND))
    parts.append("{i}// then the internal matrix J + diag".format(i=IND))
    for j, x in enumerate(INTERNAL_DIAG):
        parts.append("{i}let d{j} := 0x{x:064x}".format(i=IND, j=j, x=x))
    for r in range(ROUNDS_F_HALF, ROUNDS_F_HALF + ROUNDS_P):
        parts.append("{i}// partial round {r}".format(i=IND, r=r))
        parts.append(partial_round(r))
    for r in range(ROUNDS_F_HALF + ROUNDS_P, 2 * ROUNDS_F_HALF + ROUNDS_P):
        parts.append("{i}// full round {r}".format(i=IND, r=r))
        parts.append(full_round(r))
    return "\n".join(parts)


TEMPLATE = '''// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {IPoseidon2} from "../interfaces/IPoseidon2.sol";

/// @title Poseidon2 over the BN254 scalar field, t = 4, Barretenberg parameters.
/// @notice Generated by reference/noir/tools/gen_poseidon2_sol.py; do not edit by hand.
///         The sponge is Barretenberg's FieldSponge: capacity element = n << 64, a
///         permutation before absorbing element i whenever i > 0 and i % 3 == 0, and a
///         final permutation; output is state element 0. `reference/noir/poseidon2.py` is the
///         executable definition and `reference/vectors/noir/poseidon2.json` the vectors.
contract Poseidon2 is IPoseidon2 {
    error NotInField();

    uint256 internal constant P = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    uint256 internal constant RATE = 3;

    function hash(uint256[] calldata inputs) external pure returns (uint256) {
        uint256 n = inputs.length;
        uint256[4] memory s;
        s[3] = n << 64;
        for (uint256 i = 0; i < n; i++) {
            uint256 x = inputs[i];
            if (x >= P) revert NotInField();
            if (i > 0 && i % RATE == 0) s = _permute(s);
            s[i % RATE] = addmod(s[i % RATE], x, P);
        }
        return _permute(s)[0];
    }

    function permutation(uint256[4] calldata state) external pure returns (uint256[4] memory) {
        uint256[4] memory s = state;
        for (uint256 i = 0; i < 4; i++) {
            if (s[i] >= P) revert NotInField();
        }
        return _permute(s);
    }

    /// @dev The whole permutation, straight-line: 4 full rounds, 56 partial rounds and 4
    ///      full rounds, with every round constant a literal in the Yul. Unrolling costs
    ///      code size and buys the loop's counter, bounds check and address arithmetic
    ///      back at every one of the 64 rounds; keeping the constants in the instruction
    ///      stream removes the 8320-byte table, the `codecopy` that materialised it and
    ///      an `mload` per round. `ext` (Poseidon2's M4) and the S-box (x^5) are written
    ///      out at each site rather than kept as Yul functions, for the same reason.
    function _permute(uint256[4] memory s) internal pure returns (uint256[4] memory out) {
        assembly ("memory-safe") {
            let a := mload(s)
            let b := mload(add(s, 32))
            let c := mload(add(s, 64))
            let d := mload(add(s, 96))
<<ROUNDS>>
            mstore(out, a)
            mstore(add(out, 32), b)
            mstore(add(out, 64), c)
            mstore(add(out, 96), d)
        }
    }
}
'''


def main():
    assert len(ROUND_CONSTANTS) == 2 * ROUNDS_F_HALF + ROUNDS_P
    assert len(INTERNAL_DIAG) == 4
    body = TEMPLATE.replace("<<ROUNDS>>", rounds())
    path = os.path.join(HERE, "..", "..", "..", "src", "noir", "lib", "Poseidon2.sol")
    with open(path, "w") as f:
        f.write(body)
    print(path, len(body.splitlines()), "lines,", 2 * ROUNDS_F_HALF + ROUNDS_P, "rounds unrolled")


if __name__ == "__main__":
    main()
