"""Write noir/pbear/src/withhold_cases.nr: random tallies with withheld projects, each
with the transcript and result of `reference/withhold.py`, which runs the unchanged
`pbear.py` on padded ballots. The Noir tests replay every transcript through
`tally_step` in the test profile (E = 8, M = 4) and compare the funded order.

Usage, from `reference/`: python3 -m noir.tools.noir_withhold_cases [cases]
"""

import os
import random
import sys

from ballots import pack
from pbear import NONE
from withhold import WITHHELD, reference_transcript

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "..", "..", "noir", "pbear", "src", "withhold_cases.nr")
E, M, PER_TEST = 8, 4, 10


def random_ballot(rng, m):
    """A competition ranking with ties; a third of the voters withhold everything they
    left unranked, a third some of it, a third nothing."""
    order = list(range(m))
    rng.shuffle(order)
    ranks, rank = [0] * m, 1
    for pos, c in enumerate(order[: rng.randint(0, m)]):
        if pos == 0 or rng.random() < 0.6:
            rank = pos + 1
        ranks[c] = rank
    habit = rng.randrange(3)
    return [WITHHELD if r == 0 and (habit == 0 or (habit == 1 and rng.random() < 0.5)) else r for r in ranks]


def entry(rng, m):
    weight = rng.randint(0, 12)
    return (weight, None if rng.random() < 0.15 else random_ballot(rng, m))


def case(rng):
    m = rng.randint(1, M)
    costs = [rng.randint(1, 10) for _ in range(m)]
    public = [entry(rng, m) for _ in range(rng.randint(0, 3))]
    sealed = [entry(rng, m) for _ in range(rng.randint(0, E))]
    budget = sum(w for w, _ in public + sealed) + rng.randint(0, 6)
    funded, transcript = reference_transcript(costs, public, sealed, budget)
    return m, costs, sealed, budget, funded, transcript


def noir(index, m, costs, sealed, budget, funded, transcript):
    # A sealed entry without a usable ballot holds no weight in the circuit's state.
    weights = [w if b is not None else 0 for w, b in sealed] + [0] * (E - len(sealed))
    ballots = [pack(b) if b is not None else 0 for _, b in sealed] + [0] * (E - len(sealed))
    lines = [
        f"    // case {index}: costs {costs}, sealed {sealed}, budget {budget}",
        "    {",
        f"        let mut s = empty_state::<{E}, {M}>({m}, {budget});",
        f"        s.weights = {weights};",
        "        s.ballots = [" + ", ".join(hex(b) for b in ballots) + "];",
        f"        let costs = {costs + [0] * (M - m)};",
        "        let ranks = ranks_of(s);",
    ]
    for step in transcript:
        level, support, best, total = step[0], step[1 : m + 1], step[m + 1], step[m + 2]
        best = "NONE" if best == NONE else best
        lines.append(
            f"        s = tally_step(s, costs, Step {{ level: {level}, pub_support: {support + [0] * (M - m)}, "
            f"best: {best}, total: {total} }}, ranks);"
        )
    lines += [
        # A done or exhausted state absorbs nothing; any other state rejects this step.
        f"        s = tally_step(s, costs, Step {{ level: 0, pub_support: [0; {M}], best: NONE, total: 0 }}, ranks);",
        "        assert(s.done);",
        f"        assert(s.funded_count == {len(funded)});",
    ]
    lines += [f"        assert(s.funded_order[{j}] == {c});" for j, c in enumerate(funded)]
    lines.append(f"        assert(s.spent == {sum(costs[c] for c in funded)});")
    lines.append("    }")
    return "\n".join(lines)


def main(count):
    rng = random.Random(255)
    cases = [case(rng) for _ in range(count)]
    withheld = sum(1 for c in cases if any(b is not None and WITHHELD in b for _, b in c[2]))
    out = [
        "//! Generated by reference/noir/tools/noir_withhold_cases.py; do not edit.",
        f"//! {count} random tallies, {withheld} of them with withheld projects in the sealed block,",
        "//! replayed against the transcript and result of reference/withhold.py.",
        "",
        "use crate::{empty_state, ranks_of, Step, tally_step};",
        "use sealed::NONE;",
    ]
    for start in range(0, count, PER_TEST):
        out += ["", "#[test]", f"fn withhold_cases_{start // PER_TEST}() {{"]
        out += [noir(start + k, *c) for k, c in enumerate(cases[start : start + PER_TEST])]
        out.append("}")
    with open(OUT, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {count} cases ({withheld} with withheld projects) to {os.path.normpath(OUT)}")


if __name__ == "__main__":
    main(int(sys.argv[1]) if len(sys.argv) > 1 else 120)
