#!/usr/bin/env bash
# noir/scripts/build.sh [--check] [test|default]
#   without --check: ACIR, verification keys and Solidity verifiers.
#   with --check: recompute each verification key from the *committed* ACIR in
#     artifacts/<profile>/ and compare its vk_hash with the committed one; nothing is
#     written. Run it whenever noir/sealed or noir/pbear change: a circuit change moves
#     the vk, and then the verifiers and the proofs under noir/proofs/ are stale.
set -euo pipefail
cd "$(dirname "$0")/.."
. scripts/env.sh
check=0
if [ "${1:-}" = "--check" ]; then check=1; shift; fi
profile="${1:-default}"
case "$profile" in
  test) dest="../test/noir/verifiers"; suffix="Test" ;;
  default) dest="../src/noir/verifiers"; suffix="" ;;
  *) echo "profile must be test or default" >&2; exit 1 ;;
esac

if [ "$check" = 1 ]; then
  tmp="$(mktemp -d)"
  trap 'rm -rf "$tmp"' EXIT
  status=0
  for kind in ingest tally; do
    bb write_vk -b "artifacts/$profile/$kind.json" -o "$tmp/$kind" -t evm
    if cmp -s "$tmp/$kind/vk_hash" "artifacts/$profile/$kind.vk_hash"; then
      echo "ok   $profile/$kind: vk_hash matches artifacts/$profile/$kind.vk_hash"
    else
      echo "FAIL $profile/$kind: vk_hash differs from artifacts/$profile/$kind.vk_hash" >&2
      status=1
    fi
  done
  exit "$status"
fi

nargo compile --workspace
mkdir -p "artifacts/$profile" "$dest"
for kind in ingest tally; do
  pkg="${kind}_${profile}"
  # strip the debug symbols and the file map: they are large, they move with every
  # unrelated source edit, and neither bb nor the contracts read them.
  jq 'del(.debug_symbols, .file_map)' "target/$pkg.json" > "artifacts/$profile/$kind.json"
  bb write_vk -b "artifacts/$profile/$kind.json" -o "artifacts/$profile/$kind" -t evm
  # bb writes <out>/vk and <out>/vk_hash when -o is a directory
  mv "artifacts/$profile/$kind/vk" "artifacts/$profile/$kind.vk"
  mv "artifacts/$profile/$kind/vk_hash" "artifacts/$profile/$kind.vk_hash"
  rmdir "artifacts/$profile/$kind"
  name="$(tr '[:lower:]' '[:upper:]' <<< "${kind:0:1}")${kind:1}Verifier$suffix"
  bb write_solidity_verifier -k "artifacts/$profile/$kind.vk" -o "$dest/$name.sol" -t evm --optimized
  sed -i "s/contract HonkVerifier is IVerifier/contract $name is IVerifier/" "$dest/$name.sol"
  sed -i '1i // Generated by noir/scripts/build.sh from noir/artifacts/'"$profile/$kind"'.vk with bb 5.0.0. Do not edit.' "$dest/$name.sol"
done
echo "built $profile: artifacts/$profile, $dest"
