#!/usr/bin/env bash
# noir/scripts/build.sh [test|default]: ACIR, verification keys and Solidity verifiers.
set -euo pipefail
cd "$(dirname "$0")/.."
. scripts/env.sh
profile="${1:-default}"
case "$profile" in
  test) dest="../test/verifiers"; suffix="Test" ;;
  default) dest="../src/verifiers"; suffix="" ;;
  *) echo "profile must be test or default" >&2; exit 1 ;;
esac
nargo compile --workspace
mkdir -p "artifacts/$profile" "$dest"
for kind in ingest tally; do
  pkg="${kind}_${profile}"
  cp "target/$pkg.json" "artifacts/$profile/$kind.json"
  bb write_vk -b "artifacts/$profile/$kind.json" -o "artifacts/$profile/$kind" -t evm
  # bb writes <out>/vk and <out>/vk_hash when -o is a directory
  mv "artifacts/$profile/$kind/vk" "artifacts/$profile/$kind.vk"
  mv "artifacts/$profile/$kind/vk_hash" "artifacts/$profile/$kind.vk_hash"
  rmdir "artifacts/$profile/$kind"
  name="$(tr '[:lower:]' '[:upper:]' <<< "${kind:0:1}")${kind:1}Verifier$suffix"
  bb write_solidity_verifier -k "artifacts/$profile/$kind.vk" -o "$dest/$name.sol" -t evm --optimized
  sed -i "s/contract HonkVerifier is IVerifier/contract $name is IVerifier/" "$dest/$name.sol"
  sed -i '1i // Generated by noir/scripts/build.sh from noir/artifacts/'"$profile/$kind"'.vk with bb 5.0.0. Do not edit.' "$dest/$name.sol"
done
echo "built $profile: artifacts/$profile, $dest"
