"""Fetch Barretenberg's Poseidon2 BN254 parameters and write poseidon2_params.py.

Usage: python3 reference/tools/extract_poseidon2_params.py [path-to-header]
Without a path the header is downloaded from aztec-packages master.
"""

import hashlib
import re
import sys
import urllib.request

URL = (
    "https://raw.githubusercontent.com/AztecProtocol/aztec-packages/master/"
    "barretenberg/cpp/src/barretenberg/crypto/poseidon2/poseidon2_params.hpp"
)
HEX = re.compile(r"0x[0-9a-fA-F]{1,64}")


def hex_after(text, name, count):
    start = text.index(name)
    values = [int(h, 16) for h in HEX.findall(text[start:])[:count]]
    if len(values) != count:
        raise SystemExit(f"expected {count} constants after {name}, found {len(values)}")
    return values


def main(argv):
    if len(argv) > 1:
        raw = open(argv[1], "rb").read()
    else:
        raw = urllib.request.urlopen(URL).read()
    text = raw.decode()
    struct = text[text.index("Poseidon2Bn254ScalarFieldParams") :]
    diag = hex_after(struct, "internal_matrix_diagonal_minus_one", 4)
    rc = hex_after(struct, "round_constants", 64 * 4)
    rounds = [rc[i * 4 : (i + 1) * 4] for i in range(64)]
    with open("reference/poseidon2_params.py", "w") as f:
        f.write('"""Generated by tools/extract_poseidon2_params.py; do not edit.\n\n')
        f.write(f"Source: {URL}\nsha256 of the header: {hashlib.sha256(raw).hexdigest()}\n")
        f.write('"""\n\n')
        f.write("INTERNAL_DIAG = [\n" + "".join(f"    {v:#x},\n" for v in diag) + "]\n\n")
        f.write("ROUND_CONSTANTS = [\n")
        for row in rounds:
            f.write("    [" + ", ".join(f"{v:#x}" for v in row) + "],\n")
        f.write("]\n")


if __name__ == "__main__":
    main(sys.argv)
