"""Emit src/lib/Poseidon2.sol from reference/poseidon2_params.py.

Usage (from the repository root): python3 reference/tools/gen_poseidon2_sol.py
The constants blob is 64 rounds x 4 round constants followed by the 4 internal-matrix
diagonal terms, 32-byte big-endian words, so word i of the blob is at byte offset 32*i.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, ".."))

from poseidon2_params import INTERNAL_DIAG, ROUND_CONSTANTS  # noqa: E402

TEMPLATE = '''// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {IPoseidon2} from "../interfaces/IPoseidon2.sol";

/// @title Poseidon2 over the BN254 scalar field, t = 4, Barretenberg parameters.
/// @notice Generated by reference/tools/gen_poseidon2_sol.py; do not edit by hand.
///         The sponge is Barretenberg's FieldSponge: capacity element = n << 64, a
///         permutation before absorbing element i whenever i > 0 and i %% 3 == 0, and a
///         final permutation; output is state element 0. `reference/poseidon2.py` is the
///         executable definition and `reference/vectors/poseidon2.json` the vectors.
contract Poseidon2 is IPoseidon2 {
    error NotInField();

    uint256 internal constant P = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    uint256 internal constant RATE = 3;
    uint256 internal constant ROUNDS_F_HALF = 4;
    uint256 internal constant ROUNDS_P = 56;
    /// @dev 260 words: round constants [r][i] at word 4r + i, diagonal at words 256..259.
    bytes internal constant PARAMS = hex"%(blob)s";

    function hash(uint256[] calldata inputs) external pure returns (uint256) {
        uint256 n = inputs.length;
        uint256[4] memory s;
        s[3] = n << 64;
        bytes memory params = PARAMS;
        for (uint256 i = 0; i < n; i++) {
            uint256 x = inputs[i];
            if (x >= P) revert NotInField();
            if (i > 0 && i %% RATE == 0) s = _permute(s, params);
            s[i %% RATE] = addmod(s[i %% RATE], x, P);
        }
        return _permute(s, params)[0];
    }

    function permutation(uint256[4] calldata state) external pure returns (uint256[4] memory) {
        uint256[4] memory s = state;
        for (uint256 i = 0; i < 4; i++) {
            if (s[i] >= P) revert NotInField();
        }
        return _permute(s, PARAMS);
    }

    /// @dev `ext` (Poseidon2's M4) and the S-box (x^5) are inlined at each call site rather
    ///      than kept as Yul functions: with only a handful of call sites in the whole
    ///      permutation (loop bodies are not unrolled), inlining costs little code size but
    ///      removes per-call JUMP/stack-shuffle overhead, which is material at 64 rounds.
    ///      `params` is copied from the code constant once by the caller and threaded through
    ///      so that hashing more than RATE elements does not re-copy the 8320-byte table per
    ///      permutation.
    function _permute(uint256[4] memory s, bytes memory params) internal pure returns (uint256[4] memory out) {
        assembly ("memory-safe") {
            let rc := add(params, 32)
            let a := mload(s)
            let b := mload(add(s, 32))
            let c := mload(add(s, 64))
            let d := mload(add(s, 96))
            {
                let t0 := addmod(a, b, P)
                let t1 := addmod(c, d, P)
                let t2 := addmod(addmod(b, b, P), t1, P)
                let t3 := addmod(addmod(d, d, P), t0, P)
                let t4 := addmod(mulmod(4, t1, P), t3, P)
                let t5 := addmod(mulmod(4, t0, P), t2, P)
                a := addmod(t3, t5, P)
                b := t5
                c := addmod(t2, t4, P)
                d := t4
            }
            // first half of the full rounds
            for { let r := 0 } lt(r, ROUNDS_F_HALF) { r := add(r, 1) } {
                let base := add(rc, mul(r, 128))
                {
                    let x := addmod(a, mload(base), P)
                    let x2 := mulmod(x, x, P)
                    a := mulmod(mulmod(x2, x2, P), x, P)
                }
                {
                    let x := addmod(b, mload(add(base, 32)), P)
                    let x2 := mulmod(x, x, P)
                    b := mulmod(mulmod(x2, x2, P), x, P)
                }
                {
                    let x := addmod(c, mload(add(base, 64)), P)
                    let x2 := mulmod(x, x, P)
                    c := mulmod(mulmod(x2, x2, P), x, P)
                }
                {
                    let x := addmod(d, mload(add(base, 96)), P)
                    let x2 := mulmod(x, x, P)
                    d := mulmod(mulmod(x2, x2, P), x, P)
                }
                {
                    let t0 := addmod(a, b, P)
                    let t1 := addmod(c, d, P)
                    let t2 := addmod(addmod(b, b, P), t1, P)
                    let t3 := addmod(addmod(d, d, P), t0, P)
                    let t4 := addmod(mulmod(4, t1, P), t3, P)
                    let t5 := addmod(mulmod(4, t0, P), t2, P)
                    a := addmod(t3, t5, P)
                    b := t5
                    c := addmod(t2, t4, P)
                    d := t4
                }
            }
            // partial rounds: constant and S-box on element 0, internal matrix J + diag
            let d0 := mload(add(rc, 8192))
            let d1 := mload(add(rc, 8224))
            let d2 := mload(add(rc, 8256))
            let d3 := mload(add(rc, 8288))
            for { let r := ROUNDS_F_HALF } lt(r, add(ROUNDS_F_HALF, ROUNDS_P)) { r := add(r, 1) } {
                {
                    let x := addmod(a, mload(add(rc, mul(r, 128))), P)
                    let x2 := mulmod(x, x, P)
                    a := mulmod(mulmod(x2, x2, P), x, P)
                }
                let sum := addmod(addmod(a, b, P), addmod(c, d, P), P)
                a := addmod(mulmod(a, d0, P), sum, P)
                b := addmod(mulmod(b, d1, P), sum, P)
                c := addmod(mulmod(c, d2, P), sum, P)
                d := addmod(mulmod(d, d3, P), sum, P)
            }
            // second half of the full rounds
            for { let r := add(ROUNDS_F_HALF, ROUNDS_P) } lt(r, add(mul(ROUNDS_F_HALF, 2), ROUNDS_P)) { r := add(r, 1) } {
                let base := add(rc, mul(r, 128))
                {
                    let x := addmod(a, mload(base), P)
                    let x2 := mulmod(x, x, P)
                    a := mulmod(mulmod(x2, x2, P), x, P)
                }
                {
                    let x := addmod(b, mload(add(base, 32)), P)
                    let x2 := mulmod(x, x, P)
                    b := mulmod(mulmod(x2, x2, P), x, P)
                }
                {
                    let x := addmod(c, mload(add(base, 64)), P)
                    let x2 := mulmod(x, x, P)
                    c := mulmod(mulmod(x2, x2, P), x, P)
                }
                {
                    let x := addmod(d, mload(add(base, 96)), P)
                    let x2 := mulmod(x, x, P)
                    d := mulmod(mulmod(x2, x2, P), x, P)
                }
                {
                    let t0 := addmod(a, b, P)
                    let t1 := addmod(c, d, P)
                    let t2 := addmod(addmod(b, b, P), t1, P)
                    let t3 := addmod(addmod(d, d, P), t0, P)
                    let t4 := addmod(mulmod(4, t1, P), t3, P)
                    let t5 := addmod(mulmod(4, t0, P), t2, P)
                    a := addmod(t3, t5, P)
                    b := t5
                    c := addmod(t2, t4, P)
                    d := t4
                }
            }
            mstore(out, a)
            mstore(add(out, 32), b)
            mstore(add(out, 64), c)
            mstore(add(out, 96), d)
        }
    }
}
'''


def main():
    words = [c for row in ROUND_CONSTANTS for c in row] + list(INTERNAL_DIAG)
    assert len(words) == 260
    blob = "".join(format(w, "064x") for w in words)
    path = os.path.join(HERE, "..", "..", "src", "lib", "Poseidon2.sol")
    with open(path, "w") as f:
        f.write(TEMPLATE % {"blob": blob})
    print(path, len(blob) // 2, "bytes of constants")


if __name__ == "__main__":
    main()
